### ISSUE TITLE
intronerate.py IndexError: list index out of range

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [chrisjackson-pellicle/hybpiper-nf#9]
Hi,

this error caused the nextflow pipline to exit. The sample in question, 80069 has a genes_with_seqs.txt file with normal looking lines.

from intronerate task command.log:

Traceback (most recent call last):
  File "/HybPiper/intronerate.py", line 405, in <module>
    main()
  File "/HybPiper/intronerate.py", line 349, in main
    genelist = [x.split()[0] for x in open('genes_with_seqs.txt').readlines()]
  File "/HybPiper/intronerate.py", line 349, in <listcomp>
    genelist = [x.split()[0] for x in open('genes_with_seqs.txt').readlines()]
IndexError: list index out of range

I suspect that intronerate.py may have been opening the file while it was still being written by the previous nf task, due to slow I/O?

Thanks,

Theo

**Comment by chrisjackson-pellicle** [comment]
Hi Theo,

The `hybpiper-nf` pipeline has been updated to use HybPiper version 2. The `intronerate.py` script no longer exists in version 2, and your issue should no longer occur.

Cheers,

Chris
